package org.example.corba;
/**
* IServidorCorbaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceCorba.idl
* Terça-feira, 12 de Setembro de 2023 13h46min01s BRT
*/

public abstract class IServidorCorbaPOA extends org.omg.PortableServer.Servant
 implements IServidorCorbaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("envia", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // IServidorCorba/envia
       {
         boolean mensagem = in.read_boolean ();
         this.envia (mensagem);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:IServidorCorba:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IServidorCorba _this() 
  {
    return IServidorCorbaHelper.narrow(
    super._this_object());
  }

  public IServidorCorba _this(org.omg.CORBA.ORB orb) 
  {
    return IServidorCorbaHelper.narrow(
    super._this_object(orb));
  }


} // class IServidorCorbaPOA
