package org.example.corba;
/**
* IServidorCorbaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceCorba.idl
* Terça-feira, 12 de Setembro de 2023 13h46min01s BRT
*/

abstract public class IServidorCorbaHelper
{
  private static String  _id = "IDL:IServidorCorba:1.0";

  public static void insert (org.omg.CORBA.Any a, IServidorCorba that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static IServidorCorba extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (IServidorCorbaHelper.id (), "IServidorCorba");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static IServidorCorba read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IServidorCorbaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, IServidorCorba value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static IServidorCorba narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof IServidorCorba)
      return (IServidorCorba)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _IServidorCorbaStub stub = new _IServidorCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static IServidorCorba unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof IServidorCorba)
      return (IServidorCorba)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _IServidorCorbaStub stub = new _IServidorCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
