package org.example.corba;
/**package org.example.corba;
* IServidorCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceCorba.idl
* Terça-feira, 12 de Setembro de 2023 13h46min01s BRT
*/

public interface IServidorCorbaOperations 
{
  void envia (boolean mensagem);
} // interface IServidorCorbaOperations
