package org.example.corba;
/**
* IServidorCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from InterfaceCorba.idl
* Terça-feira, 12 de Setembro de 2023 13h46min01s BRT
*/

public final class IServidorCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public IServidorCorba value = null;

  public IServidorCorbaHolder ()
  {
  }

  public IServidorCorbaHolder (IServidorCorba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IServidorCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IServidorCorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IServidorCorbaHelper.type ();
  }

}
